storage:
  data_dir: "userdata"

products:
  vip1:
    duration_days: 31
    display_name: "&dVIP I"
    material: "GOLD_INGOT"
    lore:
      - "&7價格: 688 金幣"
      - "&7時長: 31 天"
    cost_commands:
      - "essentials:eco take {player} 688"
    grant_commands:
      - "manuadd {player} vip_1"
    revoke_commands:
      - "manudel {player}"
  mcd1:
    duration_days: 31
    display_name: "&b月卡 I"
    material: "PAPER"
    lore:
      - "&7價格: 799 金幣"
      - "&7時長: 31 天"
    cost_commands:
      - "essentials:eco take {player} 799"
    grant_commands:
      - "manuaddsub {player} mcd_1"
    revoke_commands:
      - "manudelsub {player} mcd_1"
  bag1:
    duration_days: 0   # 0 = permanent
    display_name: "&a背包 I"
    material: "CHEST"
    lore:
      - "&7價格: 360 金幣"
      - "&7時長: 永久"
    cost_commands:
      - "essentials:eco take {player} 360"
    grant_commands:
      - "manuaddsub {player} bag_1"
    revoke_commands:
      - "manudelsub {player} bag_1"
