# NekoSuite Mail Module Configuration

storage:
  data_dir: "userdata"

settings:
  # Maximum number of mails a player can have
  max_mails_per_player: 50
  # Days before mail expires (0 = never expire)
  mail_expiry_days: 30
  # Allow players to send mail to each other
  allow_player_sending: true
  # Items that cannot be sent via mail
  blocked_items:
    - "command_block"
    - "barrier"
    - "bedrock"
    - "structure_block"

# System mail templates (can be sent via admin commands)
templates:
  welcome:
    subject: "欢迎来到Neko Server！"
    content: "感谢您加入我们的服务器，祝您游戏愉快！"
    commands:
      - "minecraft:give {player} minecraft:diamond 5"
  
  daily_reward:
    subject: "每日奖励"
    content: "这是您今天的每日奖励，感谢您的支持！"
    commands:
      - "minecraft:give {player} minecraft:gold_ingot 10"
